// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabsessionstore"
	"github.com/matlab/matlab-mcp-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABSessionStore creates a new instance of MockMATLABSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABSessionStore {
	mock := &MockMATLABSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABSessionStore is an autogenerated mock type for the MATLABSessionStore type
type MockMATLABSessionStore struct {
	mock.Mock
}

type MockMATLABSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABSessionStore) EXPECT() *MockMATLABSessionStore_Expecter {
	return &MockMATLABSessionStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockMATLABSessionStore
func (_mock *MockMATLABSessionStore) Add(client matlabsessionstore.MATLABSessionClientWithCleanup, correlationID string) entities.SessionID {
	ret := _mock.Called(client, correlationID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 entities.SessionID
	if returnFunc, ok := ret.Get(0).(func(matlabsessionstore.MATLABSessionClientWithCleanup, string) entities.SessionID); ok {
		r0 = returnFunc(client, correlationID)
	} else {
		r0 = ret.Get(0).(entities.SessionID)
	}
	return r0
}

// MockMATLABSessionStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMATLABSessionStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - client matlabsessionstore.MATLABSessionClientWithCleanup
//   - correlationID string
func (_e *MockMATLABSessionStore_Expecter) Add(client interface{}, correlationID interface{}) *MockMATLABSessionStore_Add_Call {
	return &MockMATLABSessionStore_Add_Call{Call: _e.mock.On("Add", client, correlationID)}
}

func (_c *MockMATLABSessionStore_Add_Call) Run(run func(client matlabsessionstore.MATLABSessionClientWithCleanup, correlationID string)) *MockMATLABSessionStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 matlabsessionstore.MATLABSessionClientWithCleanup
		if args[0] != nil {
			arg0 = args[0].(matlabsessionstore.MATLABSessionClientWithCleanup)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMATLABSessionStore_Add_Call) Return(sessionID entities.SessionID) *MockMATLABSessionStore_Add_Call {
	_c.Call.Return(sessionID)
	return _c
}

func (_c *MockMATLABSessionStore_Add_Call) RunAndReturn(run func(client matlabsessionstore.MATLABSessionClientWithCleanup, correlationID string) entities.SessionID) *MockMATLABSessionStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// CorrelationID provides a mock function for the type MockMATLABSessionStore
func (_mock *MockMATLABSessionStore) CorrelationID(sessionID entities.SessionID) string {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CorrelationID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(entities.SessionID) string); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMATLABSessionStore_CorrelationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CorrelationID'
type MockMATLABSessionStore_CorrelationID_Call struct {
	*mock.Call
}

// CorrelationID is a helper method to define mock.On call
//   - sessionID entities.SessionID
func (_e *MockMATLABSessionStore_Expecter) CorrelationID(sessionID interface{}) *MockMATLABSessionStore_CorrelationID_Call {
	return &MockMATLABSessionStore_CorrelationID_Call{Call: _e.mock.On("CorrelationID", sessionID)}
}

func (_c *MockMATLABSessionStore_CorrelationID_Call) Run(run func(sessionID entities.SessionID)) *MockMATLABSessionStore_CorrelationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.SessionID
		if args[0] != nil {
			arg0 = args[0].(entities.SessionID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABSessionStore_CorrelationID_Call) Return(s string) *MockMATLABSessionStore_CorrelationID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMATLABSessionStore_CorrelationID_Call) RunAndReturn(run func(sessionID entities.SessionID) string) *MockMATLABSessionStore_CorrelationID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMATLABSessionStore
func (_mock *MockMATLABSessionStore) Get(sessionID entities.SessionID) (matlabsessionstore.MATLABSessionClientWithCleanup, error) {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 matlabsessionstore.MATLABSessionClientWithCleanup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.SessionID) (matlabsessionstore.MATLABSessionClientWithCleanup, error)); ok {
		return returnFunc(sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.SessionID) matlabsessionstore.MATLABSessionClientWithCleanup); ok {
		r0 = returnFunc(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matlabsessionstore.MATLABSessionClientWithCleanup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(entities.SessionID) error); ok {
		r1 = returnFunc(sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMATLABSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - sessionID entities.SessionID
func (_e *MockMATLABSessionStore_Expecter) Get(sessionID interface{}) *MockMATLABSessionStore_Get_Call {
	return &MockMATLABSessionStore_Get_Call{Call: _e.mock.On("Get", sessionID)}
}

func (_c *MockMATLABSessionStore_Get_Call) Run(run func(sessionID entities.SessionID)) *MockMATLABSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.SessionID
		if args[0] != nil {
			arg0 = args[0].(entities.SessionID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABSessionStore_Get_Call) Return(mATLABSessionClientWithCleanup matlabsessionstore.MATLABSessionClientWithCleanup, err error) *MockMATLABSessionStore_Get_Call {
	_c.Call.Return(mATLABSessionClientWithCleanup, err)
	return _c
}

func (_c *MockMATLABSessionStore_Get_Call) RunAndReturn(run func(sessionID entities.SessionID) (matlabsessionstore.MATLABSessionClientWithCleanup, error)) *MockMATLABSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockMATLABSessionStore
func (_mock *MockMATLABSessionStore) Remove(sessionID entities.SessionID) {
	_mock.Called(sessionID)
	return
}

// MockMATLABSessionStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockMATLABSessionStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - sessionID entities.SessionID
func (_e *MockMATLABSessionStore_Expecter) Remove(sessionID interface{}) *MockMATLABSessionStore_Remove_Call {
	return &MockMATLABSessionStore_Remove_Call{Call: _e.mock.On("Remove", sessionID)}
}

func (_c *MockMATLABSessionStore_Remove_Call) Run(run func(sessionID entities.SessionID)) *MockMATLABSessionStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.SessionID
		if args[0] != nil {
			arg0 = args[0].(entities.SessionID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABSessionStore_Remove_Call) Return() *MockMATLABSessionStore_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMATLABSessionStore_Remove_Call) RunAndReturn(run func(sessionID entities.SessionID)) *MockMATLABSessionStore_Remove_Call {
	_c.Run(run)
	return _c
}
