// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry/otel"
	"github.com/matlab/matlab-mcp-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMeterProviderFactory creates a new instance of MockMeterProviderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMeterProviderFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMeterProviderFactory {
	mock := &MockMeterProviderFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMeterProviderFactory is an autogenerated mock type for the MeterProviderFactory type
type MockMeterProviderFactory struct {
	mock.Mock
}

type MockMeterProviderFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMeterProviderFactory) EXPECT() *MockMeterProviderFactory_Expecter {
	return &MockMeterProviderFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockMeterProviderFactory
func (_mock *MockMeterProviderFactory) New(exporter otel.MetricExporter, errorHandler otel.ErrorHandler, serviceName string, serviceVersion string) (otel.MeterProvider, messages.Error) {
	ret := _mock.Called(exporter, errorHandler, serviceName, serviceVersion)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 otel.MeterProvider
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(otel.MetricExporter, otel.ErrorHandler, string, string) (otel.MeterProvider, messages.Error)); ok {
		return returnFunc(exporter, errorHandler, serviceName, serviceVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(otel.MetricExporter, otel.ErrorHandler, string, string) otel.MeterProvider); ok {
		r0 = returnFunc(exporter, errorHandler, serviceName, serviceVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(otel.MeterProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(otel.MetricExporter, otel.ErrorHandler, string, string) messages.Error); ok {
		r1 = returnFunc(exporter, errorHandler, serviceName, serviceVersion)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockMeterProviderFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockMeterProviderFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - exporter otel.MetricExporter
//   - errorHandler otel.ErrorHandler
//   - serviceName string
//   - serviceVersion string
func (_e *MockMeterProviderFactory_Expecter) New(exporter interface{}, errorHandler interface{}, serviceName interface{}, serviceVersion interface{}) *MockMeterProviderFactory_New_Call {
	return &MockMeterProviderFactory_New_Call{Call: _e.mock.On("New", exporter, errorHandler, serviceName, serviceVersion)}
}

func (_c *MockMeterProviderFactory_New_Call) Run(run func(exporter otel.MetricExporter, errorHandler otel.ErrorHandler, serviceName string, serviceVersion string)) *MockMeterProviderFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 otel.MetricExporter
		if args[0] != nil {
			arg0 = args[0].(otel.MetricExporter)
		}
		var arg1 otel.ErrorHandler
		if args[1] != nil {
			arg1 = args[1].(otel.ErrorHandler)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMeterProviderFactory_New_Call) Return(meterProvider otel.MeterProvider, error messages.Error) *MockMeterProviderFactory_New_Call {
	_c.Call.Return(meterProvider, error)
	return _c
}

func (_c *MockMeterProviderFactory_New_Call) RunAndReturn(run func(exporter otel.MetricExporter, errorHandler otel.ErrorHandler, serviceName string, serviceVersion string) (otel.MeterProvider, messages.Error)) *MockMeterProviderFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
