// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionCorrelationIDProvider creates a new instance of MockSessionCorrelationIDProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionCorrelationIDProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionCorrelationIDProvider {
	mock := &MockSessionCorrelationIDProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionCorrelationIDProvider is an autogenerated mock type for the SessionCorrelationIDProvider type
type MockSessionCorrelationIDProvider struct {
	mock.Mock
}

type MockSessionCorrelationIDProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionCorrelationIDProvider) EXPECT() *MockSessionCorrelationIDProvider_Expecter {
	return &MockSessionCorrelationIDProvider_Expecter{mock: &_m.Mock}
}

// CurrentCorrelationID provides a mock function for the type MockSessionCorrelationIDProvider
func (_mock *MockSessionCorrelationIDProvider) CurrentCorrelationID(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentCorrelationID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSessionCorrelationIDProvider_CurrentCorrelationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentCorrelationID'
type MockSessionCorrelationIDProvider_CurrentCorrelationID_Call struct {
	*mock.Call
}

// CurrentCorrelationID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionCorrelationIDProvider_Expecter) CurrentCorrelationID(ctx interface{}) *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call {
	return &MockSessionCorrelationIDProvider_CurrentCorrelationID_Call{Call: _e.mock.On("CurrentCorrelationID", ctx)}
}

func (_c *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call) Run(run func(ctx context.Context)) *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call) Return(s string) *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call) RunAndReturn(run func(ctx context.Context) string) *MockSessionCorrelationIDProvider_CurrentCorrelationID_Call {
	_c.Call.Return(run)
	return _c
}
