// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/entities"
	"github.com/matlab/matlab-mcp-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerFactory creates a new instance of MockLoggerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerFactory {
	mock := &MockLoggerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerFactory is an autogenerated mock type for the LoggerFactory type
type MockLoggerFactory struct {
	mock.Mock
}

type MockLoggerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerFactory) EXPECT() *MockLoggerFactory_Expecter {
	return &MockLoggerFactory_Expecter{mock: &_m.Mock}
}

// GetGlobalLogger provides a mock function for the type MockLoggerFactory
func (_mock *MockLoggerFactory) GetGlobalLogger() (entities.Logger, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalLogger")
	}

	var r0 entities.Logger
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (entities.Logger, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() entities.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Logger)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockLoggerFactory_GetGlobalLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalLogger'
type MockLoggerFactory_GetGlobalLogger_Call struct {
	*mock.Call
}

// GetGlobalLogger is a helper method to define mock.On call
func (_e *MockLoggerFactory_Expecter) GetGlobalLogger() *MockLoggerFactory_GetGlobalLogger_Call {
	return &MockLoggerFactory_GetGlobalLogger_Call{Call: _e.mock.On("GetGlobalLogger")}
}

func (_c *MockLoggerFactory_GetGlobalLogger_Call) Run(run func()) *MockLoggerFactory_GetGlobalLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerFactory_GetGlobalLogger_Call) Return(logger entities.Logger, error messages.Error) *MockLoggerFactory_GetGlobalLogger_Call {
	_c.Call.Return(logger, error)
	return _c
}

func (_c *MockLoggerFactory_GetGlobalLogger_Call) RunAndReturn(run func() (entities.Logger, messages.Error)) *MockLoggerFactory_GetGlobalLogger_Call {
	_c.Call.Return(run)
	return _c
}
