// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/entities"
	"github.com/matlab/matlab-mcp-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABManagerAdaptor creates a new instance of MockMATLABManagerAdaptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABManagerAdaptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABManagerAdaptor {
	mock := &MockMATLABManagerAdaptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABManagerAdaptor is an autogenerated mock type for the MATLABManagerAdaptor type
type MockMATLABManagerAdaptor struct {
	mock.Mock
}

type MockMATLABManagerAdaptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABManagerAdaptor) EXPECT() *MockMATLABManagerAdaptor_Expecter {
	return &MockMATLABManagerAdaptor_Expecter{mock: &_m.Mock}
}

// GetMATLABSessionClient provides a mock function for the type MockMATLABManagerAdaptor
func (_mock *MockMATLABManagerAdaptor) GetMATLABSessionClient(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) (entities.MATLABSessionClient, error) {
	ret := _mock.Called(ctx, sessionLogger, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMATLABSessionClient")
	}

	var r0 entities.MATLABSessionClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionID) (entities.MATLABSessionClient, error)); ok {
		return returnFunc(ctx, sessionLogger, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionID) entities.MATLABSessionClient); ok {
		r0 = returnFunc(ctx, sessionLogger, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MATLABSessionClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.SessionID) error); ok {
		r1 = returnFunc(ctx, sessionLogger, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABManagerAdaptor_GetMATLABSessionClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMATLABSessionClient'
type MockMATLABManagerAdaptor_GetMATLABSessionClient_Call struct {
	*mock.Call
}

// GetMATLABSessionClient is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - sessionID entities.SessionID
func (_e *MockMATLABManagerAdaptor_Expecter) GetMATLABSessionClient(ctx interface{}, sessionLogger interface{}, sessionID interface{}) *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call {
	return &MockMATLABManagerAdaptor_GetMATLABSessionClient_Call{Call: _e.mock.On("GetMATLABSessionClient", ctx, sessionLogger, sessionID)}
}

func (_c *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID)) *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.SessionID
		if args[2] != nil {
			arg2 = args[2].(entities.SessionID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call) Return(mATLABSessionClient entities.MATLABSessionClient, err error) *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call {
	_c.Call.Return(mATLABSessionClient, err)
	return _c
}

func (_c *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) (entities.MATLABSessionClient, error)) *MockMATLABManagerAdaptor_GetMATLABSessionClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionCorrelationID provides a mock function for the type MockMATLABManagerAdaptor
func (_mock *MockMATLABManagerAdaptor) GetSessionCorrelationID(sessionID entities.SessionID) string {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionCorrelationID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(entities.SessionID) string); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMATLABManagerAdaptor_GetSessionCorrelationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionCorrelationID'
type MockMATLABManagerAdaptor_GetSessionCorrelationID_Call struct {
	*mock.Call
}

// GetSessionCorrelationID is a helper method to define mock.On call
//   - sessionID entities.SessionID
func (_e *MockMATLABManagerAdaptor_Expecter) GetSessionCorrelationID(sessionID interface{}) *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call {
	return &MockMATLABManagerAdaptor_GetSessionCorrelationID_Call{Call: _e.mock.On("GetSessionCorrelationID", sessionID)}
}

func (_c *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call) Run(run func(sessionID entities.SessionID)) *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.SessionID
		if args[0] != nil {
			arg0 = args[0].(entities.SessionID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call) Return(s string) *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call) RunAndReturn(run func(sessionID entities.SessionID) string) *MockMATLABManagerAdaptor_GetSessionCorrelationID_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldRestart provides a mock function for the type MockMATLABManagerAdaptor
func (_mock *MockMATLABManagerAdaptor) ShouldRestart() (bool, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShouldRestart")
	}

	var r0 bool
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (bool, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockMATLABManagerAdaptor_ShouldRestart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRestart'
type MockMATLABManagerAdaptor_ShouldRestart_Call struct {
	*mock.Call
}

// ShouldRestart is a helper method to define mock.On call
func (_e *MockMATLABManagerAdaptor_Expecter) ShouldRestart() *MockMATLABManagerAdaptor_ShouldRestart_Call {
	return &MockMATLABManagerAdaptor_ShouldRestart_Call{Call: _e.mock.On("ShouldRestart")}
}

func (_c *MockMATLABManagerAdaptor_ShouldRestart_Call) Run(run func()) *MockMATLABManagerAdaptor_ShouldRestart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMATLABManagerAdaptor_ShouldRestart_Call) Return(b bool, error messages.Error) *MockMATLABManagerAdaptor_ShouldRestart_Call {
	_c.Call.Return(b, error)
	return _c
}

func (_c *MockMATLABManagerAdaptor_ShouldRestart_Call) RunAndReturn(run func() (bool, messages.Error)) *MockMATLABManagerAdaptor_ShouldRestart_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function for the type MockMATLABManagerAdaptor
func (_mock *MockMATLABManagerAdaptor) StartSession(ctx context.Context, logger entities.Logger) (entities.SessionID, error) {
	ret := _mock.Called(ctx, logger)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 entities.SessionID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) (entities.SessionID, error)); ok {
		return returnFunc(ctx, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) entities.SessionID); ok {
		r0 = returnFunc(ctx, logger)
	} else {
		r0 = ret.Get(0).(entities.SessionID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger) error); ok {
		r1 = returnFunc(ctx, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABManagerAdaptor_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockMATLABManagerAdaptor_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
func (_e *MockMATLABManagerAdaptor_Expecter) StartSession(ctx interface{}, logger interface{}) *MockMATLABManagerAdaptor_StartSession_Call {
	return &MockMATLABManagerAdaptor_StartSession_Call{Call: _e.mock.On("StartSession", ctx, logger)}
}

func (_c *MockMATLABManagerAdaptor_StartSession_Call) Run(run func(ctx context.Context, logger entities.Logger)) *MockMATLABManagerAdaptor_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMATLABManagerAdaptor_StartSession_Call) Return(sessionID entities.SessionID, err error) *MockMATLABManagerAdaptor_StartSession_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *MockMATLABManagerAdaptor_StartSession_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger) (entities.SessionID, error)) *MockMATLABManagerAdaptor_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// StopMATLABSession provides a mock function for the type MockMATLABManagerAdaptor
func (_mock *MockMATLABManagerAdaptor) StopMATLABSession(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) error {
	ret := _mock.Called(ctx, sessionLogger, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for StopMATLABSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionID) error); ok {
		r0 = returnFunc(ctx, sessionLogger, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMATLABManagerAdaptor_StopMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopMATLABSession'
type MockMATLABManagerAdaptor_StopMATLABSession_Call struct {
	*mock.Call
}

// StopMATLABSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - sessionID entities.SessionID
func (_e *MockMATLABManagerAdaptor_Expecter) StopMATLABSession(ctx interface{}, sessionLogger interface{}, sessionID interface{}) *MockMATLABManagerAdaptor_StopMATLABSession_Call {
	return &MockMATLABManagerAdaptor_StopMATLABSession_Call{Call: _e.mock.On("StopMATLABSession", ctx, sessionLogger, sessionID)}
}

func (_c *MockMATLABManagerAdaptor_StopMATLABSession_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID)) *MockMATLABManagerAdaptor_StopMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.SessionID
		if args[2] != nil {
			arg2 = args[2].(entities.SessionID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABManagerAdaptor_StopMATLABSession_Call) Return(err error) *MockMATLABManagerAdaptor_StopMATLABSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMATLABManagerAdaptor_StopMATLABSession_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) error) *MockMATLABManagerAdaptor_StopMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}
