// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABManager creates a new instance of MockMATLABManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABManager {
	mock := &MockMATLABManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABManager is an autogenerated mock type for the MATLABManager type
type MockMATLABManager struct {
	mock.Mock
}

type MockMATLABManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABManager) EXPECT() *MockMATLABManager_Expecter {
	return &MockMATLABManager_Expecter{mock: &_m.Mock}
}

// GetMATLABSessionClient provides a mock function for the type MockMATLABManager
func (_mock *MockMATLABManager) GetMATLABSessionClient(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) (entities.MATLABSessionClient, error) {
	ret := _mock.Called(ctx, sessionLogger, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMATLABSessionClient")
	}

	var r0 entities.MATLABSessionClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionID) (entities.MATLABSessionClient, error)); ok {
		return returnFunc(ctx, sessionLogger, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionID) entities.MATLABSessionClient); ok {
		r0 = returnFunc(ctx, sessionLogger, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MATLABSessionClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.SessionID) error); ok {
		r1 = returnFunc(ctx, sessionLogger, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABManager_GetMATLABSessionClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMATLABSessionClient'
type MockMATLABManager_GetMATLABSessionClient_Call struct {
	*mock.Call
}

// GetMATLABSessionClient is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - sessionID entities.SessionID
func (_e *MockMATLABManager_Expecter) GetMATLABSessionClient(ctx interface{}, sessionLogger interface{}, sessionID interface{}) *MockMATLABManager_GetMATLABSessionClient_Call {
	return &MockMATLABManager_GetMATLABSessionClient_Call{Call: _e.mock.On("GetMATLABSessionClient", ctx, sessionLogger, sessionID)}
}

func (_c *MockMATLABManager_GetMATLABSessionClient_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID)) *MockMATLABManager_GetMATLABSessionClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.SessionID
		if args[2] != nil {
			arg2 = args[2].(entities.SessionID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABManager_GetMATLABSessionClient_Call) Return(mATLABSessionClient entities.MATLABSessionClient, err error) *MockMATLABManager_GetMATLABSessionClient_Call {
	_c.Call.Return(mATLABSessionClient, err)
	return _c
}

func (_c *MockMATLABManager_GetMATLABSessionClient_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) (entities.MATLABSessionClient, error)) *MockMATLABManager_GetMATLABSessionClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionCorrelationID provides a mock function for the type MockMATLABManager
func (_mock *MockMATLABManager) GetSessionCorrelationID(sessionID entities.SessionID) string {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionCorrelationID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(entities.SessionID) string); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMATLABManager_GetSessionCorrelationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionCorrelationID'
type MockMATLABManager_GetSessionCorrelationID_Call struct {
	*mock.Call
}

// GetSessionCorrelationID is a helper method to define mock.On call
//   - sessionID entities.SessionID
func (_e *MockMATLABManager_Expecter) GetSessionCorrelationID(sessionID interface{}) *MockMATLABManager_GetSessionCorrelationID_Call {
	return &MockMATLABManager_GetSessionCorrelationID_Call{Call: _e.mock.On("GetSessionCorrelationID", sessionID)}
}

func (_c *MockMATLABManager_GetSessionCorrelationID_Call) Run(run func(sessionID entities.SessionID)) *MockMATLABManager_GetSessionCorrelationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.SessionID
		if args[0] != nil {
			arg0 = args[0].(entities.SessionID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABManager_GetSessionCorrelationID_Call) Return(s string) *MockMATLABManager_GetSessionCorrelationID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMATLABManager_GetSessionCorrelationID_Call) RunAndReturn(run func(sessionID entities.SessionID) string) *MockMATLABManager_GetSessionCorrelationID_Call {
	_c.Call.Return(run)
	return _c
}

// StartMATLABSession provides a mock function for the type MockMATLABManager
func (_mock *MockMATLABManager) StartMATLABSession(ctx context.Context, sessionLogger entities.Logger, startRequest entities.SessionDetails) (entities.SessionID, error) {
	ret := _mock.Called(ctx, sessionLogger, startRequest)

	if len(ret) == 0 {
		panic("no return value specified for StartMATLABSession")
	}

	var r0 entities.SessionID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionDetails) (entities.SessionID, error)); ok {
		return returnFunc(ctx, sessionLogger, startRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionDetails) entities.SessionID); ok {
		r0 = returnFunc(ctx, sessionLogger, startRequest)
	} else {
		r0 = ret.Get(0).(entities.SessionID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.SessionDetails) error); ok {
		r1 = returnFunc(ctx, sessionLogger, startRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABManager_StartMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartMATLABSession'
type MockMATLABManager_StartMATLABSession_Call struct {
	*mock.Call
}

// StartMATLABSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - startRequest entities.SessionDetails
func (_e *MockMATLABManager_Expecter) StartMATLABSession(ctx interface{}, sessionLogger interface{}, startRequest interface{}) *MockMATLABManager_StartMATLABSession_Call {
	return &MockMATLABManager_StartMATLABSession_Call{Call: _e.mock.On("StartMATLABSession", ctx, sessionLogger, startRequest)}
}

func (_c *MockMATLABManager_StartMATLABSession_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, startRequest entities.SessionDetails)) *MockMATLABManager_StartMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.SessionDetails
		if args[2] != nil {
			arg2 = args[2].(entities.SessionDetails)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABManager_StartMATLABSession_Call) Return(sessionID entities.SessionID, err error) *MockMATLABManager_StartMATLABSession_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *MockMATLABManager_StartMATLABSession_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, startRequest entities.SessionDetails) (entities.SessionID, error)) *MockMATLABManager_StartMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}

// StopMATLABSession provides a mock function for the type MockMATLABManager
func (_mock *MockMATLABManager) StopMATLABSession(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) error {
	ret := _mock.Called(ctx, sessionLogger, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for StopMATLABSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.SessionID) error); ok {
		r0 = returnFunc(ctx, sessionLogger, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMATLABManager_StopMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopMATLABSession'
type MockMATLABManager_StopMATLABSession_Call struct {
	*mock.Call
}

// StopMATLABSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - sessionID entities.SessionID
func (_e *MockMATLABManager_Expecter) StopMATLABSession(ctx interface{}, sessionLogger interface{}, sessionID interface{}) *MockMATLABManager_StopMATLABSession_Call {
	return &MockMATLABManager_StopMATLABSession_Call{Call: _e.mock.On("StopMATLABSession", ctx, sessionLogger, sessionID)}
}

func (_c *MockMATLABManager_StopMATLABSession_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID)) *MockMATLABManager_StopMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.SessionID
		if args[2] != nil {
			arg2 = args[2].(entities.SessionID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABManager_StopMATLABSession_Call) Return(err error) *MockMATLABManager_StopMATLABSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMATLABManager_StopMATLABSession_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, sessionID entities.SessionID) error) *MockMATLABManager_StopMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}
