// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/directory"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/lifecyclesignaler"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/modeselector"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/modeselector/modes/setupmatlab"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/orchestrator"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/parameter/defaultparameters/selector"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/parameter/parser"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/buildinfo"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/filesystem/files"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/globalmatlab"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/globalmatlab/sessionmanager"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/globalmatlab/sessionmanager/matlabstartingdirselector"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/http/client"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/http/server"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/logger"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlab/codeanalyzer"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlab/matlabrootselector"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/addonmanager"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/addonmanager/installationsteps"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/connectionindicator"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession"
	directory2 "github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory/matlabfiles"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processdetails"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processlauncher"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabroot"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabversion"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabsessionclient"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/matlabsessionstore"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/sessionselector"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/sessionselector/sessiondiscovery"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/matlabmanager/sessionselector/sessiondiscovery/appdatadir"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/resources/codingguidelines"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/resources/plaintextlivecodegeneration"
	server3 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/server"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/server/clientinfostore"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/server/configurator"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/server/rootpathresolver"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/server/rootstore"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/server/sdk"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools"
	evalmatlabcode2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/multisession/evalmatlabcode"
	listavailablematlabs2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/multisession/listavailablematlabs"
	startmatlabsession2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/multisession/startmatlabsession"
	stopmatlabsession2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/multisession/stopmatlabsession"
	checkmatlabcode2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/checkmatlabcode"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/custom"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/custom/loader"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/custom/loader/validator"
	detectmatlabtoolboxes2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/detectmatlabtoolboxes"
	evalmatlabcode3 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/evalmatlabcode"
	runmatlabfile2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/runmatlabfile"
	runmatlabtestfile2 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/singlesession/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/messagecatalog"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/os"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/resourcelimit"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry/otel/instruments"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry/otel/meter/exporter"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry/otel/meter/provider"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/watchdog"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/watchdog/process"
	"github.com/matlab/matlab-mcp-server/internal/entities"
	"github.com/matlab/matlab-mcp-server/internal/facades/filefacade"
	"github.com/matlab/matlab-mcp-server/internal/facades/iofacade"
	"github.com/matlab/matlab-mcp-server/internal/facades/osfacade"
	"github.com/matlab/matlab-mcp-server/internal/facades/registryfacade"
	"github.com/matlab/matlab-mcp-server/internal/facades/unix"
	"github.com/matlab/matlab-mcp-server/internal/usecases/checkmatlabcode"
	"github.com/matlab/matlab-mcp-server/internal/usecases/detectmatlabtoolboxes"
	"github.com/matlab/matlab-mcp-server/internal/usecases/evalcustomtool"
	"github.com/matlab/matlab-mcp-server/internal/usecases/evalcustomtool/functioncall"
	"github.com/matlab/matlab-mcp-server/internal/usecases/evalmatlabcode"
	"github.com/matlab/matlab-mcp-server/internal/usecases/listavailablematlabs"
	"github.com/matlab/matlab-mcp-server/internal/usecases/runmatlabfile"
	"github.com/matlab/matlab-mcp-server/internal/usecases/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-server/internal/usecases/startmatlabsession"
	"github.com/matlab/matlab-mcp-server/internal/usecases/stopmatlabsession"
	"github.com/matlab/matlab-mcp-server/internal/usecases/utils/pathvalidator"
	watchdog2 "github.com/matlab/matlab-mcp-server/internal/watchdog"
	"github.com/matlab/matlab-mcp-server/internal/watchdog/processhandler"
	client2 "github.com/matlab/matlab-mcp-server/internal/watchdog/transport/client"
	server2 "github.com/matlab/matlab-mcp-server/internal/watchdog/transport/server"
	"github.com/matlab/matlab-mcp-server/internal/watchdog/transport/server/handler"
	"github.com/matlab/matlab-mcp-server/internal/watchdog/transport/socket"
)

// Injectors from wire.go:

func Initialize(serverDefinition ApplicationDefinition) *Application {
	osFacade := osfacade.New()
	messageCatalog := messagecatalog.New()
	selectorSelector := selector.New(serverDefinition, messageCatalog)
	parserParser := parser.New(osFacade, selectorSelector, serverDefinition)
	buildInfo := buildinfo.New(osFacade)
	factory := config.NewFactory(parserParser, osFacade, buildInfo)
	filesFactory := files.NewFactory(osFacade)
	directoryFactory := directory.NewFactory(factory, filesFactory, osFacade)
	loggerFactory := logger.NewFactory(factory, directoryFactory, filesFactory, osFacade)
	exporterFactory := exporter.NewFactory(loggerFactory, factory, osFacade)
	lifecycleSignaler := lifecyclesignaler.New()
	providerFactory := provider.NewFactory(loggerFactory, factory, lifecycleSignaler)
	instrumentsFactory := instruments.NewFactory()
	registryFacade := registryfacade.New()
	osOS := os.New(osFacade, registryFacade)
	fileFacade := filefacade.New()
	getter := matlabroot.New(osFacade, fileFacade)
	ioFacade := iofacade.New()
	matlabversionGetter := matlabversion.New(osFacade, ioFacade)
	matlabLocator := matlablocator.New(getter, matlabversionGetter)
	matlabFiles := matlabfiles.New()
	factory2 := directory2.NewFactory(osFacade, directoryFactory, matlabFiles, factory)
	processDetails := processdetails.New(osFacade)
	matlabProcessLauncher := processlauncher.New()
	processFactory := process.New(osFacade, loggerFactory, directoryFactory, factory)
	clientFactory := client.NewFactory()
	factory3 := client2.NewFactory(osFacade, loggerFactory, clientFactory)
	socketFactory := socket.NewFactory(directoryFactory, osFacade)
	watchdogWatchdog := watchdog.New(processFactory, factory3, loggerFactory, socketFactory)
	starter := localmatlabsession.NewStarter(factory2, processDetails, matlabProcessLauncher, watchdogWatchdog)
	matlabServices := matlabservices.New(matlabLocator, starter)
	store := matlabsessionstore.New(loggerFactory, lifecycleSignaler)
	matlabsessionclientFactory := matlabsessionclient.NewFactory(clientFactory)
	appdatadirGetter := appdatadir.New(osFacade)
	sessionDiscoverer := sessiondiscovery.New(appdatadirGetter, osFacade)
	sessionSelector := sessionselector.New(factory, sessionDiscoverer)
	clientInfoStore := clientinfostore.New()
	connectionIndicator := connectionindicator.New(messageCatalog)
	matlabManager := matlabmanager.New(factory, matlabServices, store, matlabsessionclientFactory, sessionSelector, clientInfoStore, connectionIndicator)
	matlabRootSelector := matlabrootselector.New(factory, matlabManager)
	rootStore := rootstore.New()
	rootPathResolver := rootpathresolver.New(osFacade)
	matlabStartingDirSelector := matlabstartingdirselector.New(factory, osFacade, rootStore, rootPathResolver)
	sessionManager := sessionmanager.New(matlabManager, factory, matlabRootSelector, matlabStartingDirSelector)
	globalMATLAB := globalmatlab.New(sessionManager, loggerFactory)
	telemetryFactory := telemetry.NewFactory(loggerFactory, factory, exporterFactory, providerFactory, instrumentsFactory, directoryFactory, osFacade, osOS, serverDefinition, globalMATLAB)
	processManager := os.NewProcessManager(osFacade)
	processHandler := processhandler.New(loggerFactory, processManager)
	handlerFactory := handler.NewFactory(loggerFactory, processHandler)
	serverFactory := server.NewFactory(osFacade)
	factory4 := server2.NewFactory(serverFactory, loggerFactory, handlerFactory)
	watchdog3 := watchdog2.New(loggerFactory, osFacade, processHandler, processManager, handlerFactory, factory4, socketFactory)
	sdkFactory := sdk.NewFactory(factory, serverDefinition, rootStore, clientInfoStore, loggerFactory, globalMATLAB, telemetryFactory)
	usecase := listavailablematlabs.New(matlabManager)
	tool := listavailablematlabs2.New(loggerFactory, telemetryFactory, usecase)
	startmatlabsessionUsecase := startmatlabsession.New(matlabManager)
	startmatlabsessionTool := startmatlabsession2.New(loggerFactory, telemetryFactory, factory, startmatlabsessionUsecase)
	stopmatlabsessionUsecase := stopmatlabsession.New(matlabManager)
	stopmatlabsessionTool := stopmatlabsession2.New(loggerFactory, telemetryFactory, stopmatlabsessionUsecase)
	pathValidator := pathvalidator.New(osFacade)
	evalmatlabcodeUsecase := evalmatlabcode.New(pathValidator)
	evalmatlabcodeTool := evalmatlabcode2.New(loggerFactory, telemetryFactory, factory, evalmatlabcodeUsecase, matlabManager)
	tool2 := evalmatlabcode3.New(loggerFactory, telemetryFactory, factory, evalmatlabcodeUsecase, globalMATLAB)
	analyzer := codeanalyzer.New()
	checkmatlabcodeUsecase := checkmatlabcode.New(pathValidator, analyzer)
	checkmatlabcodeTool := checkmatlabcode2.New(loggerFactory, telemetryFactory, checkmatlabcodeUsecase, globalMATLAB)
	detectmatlabtoolboxesUsecase := detectmatlabtoolboxes.New()
	detectmatlabtoolboxesTool := detectmatlabtoolboxes2.New(loggerFactory, telemetryFactory, detectmatlabtoolboxesUsecase, globalMATLAB)
	runmatlabfileUsecase := runmatlabfile.New(pathValidator)
	runmatlabfileTool := runmatlabfile2.New(loggerFactory, telemetryFactory, factory, runmatlabfileUsecase, globalMATLAB)
	runmatlabtestfileUsecase := runmatlabtestfile.New(pathValidator)
	runmatlabtestfileTool := runmatlabtestfile2.New(loggerFactory, telemetryFactory, runmatlabtestfileUsecase, globalMATLAB)
	resource := codingguidelines.New(loggerFactory)
	plaintextlivecodegenerationResource := plaintextlivecodegeneration.New(loggerFactory)
	validatorValidator := validator.NewValidator()
	loaderLoader := loader.NewLoader(osFacade, loggerFactory, validatorValidator)
	assembler := functioncall.NewAssembler()
	evalcustomtoolUsecase := evalcustomtool.New(assembler)
	customFactory := custom.NewFactory(loaderLoader, loggerFactory, telemetryFactory, evalcustomtoolUsecase, globalMATLAB, factory)
	configuratorConfigurator := configurator.New(factory, serverDefinition, tool, startmatlabsessionTool, stopmatlabsessionTool, evalmatlabcodeTool, tool2, checkmatlabcodeTool, detectmatlabtoolboxesTool, runmatlabfileTool, runmatlabtestfileTool, resource, plaintextlivecodegenerationResource, customFactory)
	serverServer := server3.New(sdkFactory, loggerFactory, lifecycleSignaler, configuratorConfigurator)
	unixFacade := unix.New()
	manager := resourcelimit.New(loggerFactory, unixFacade)
	orchestratorOrchestrator := orchestrator.New(messageCatalog, lifecycleSignaler, serverDefinition, factory, serverServer, watchdogWatchdog, loggerFactory, telemetryFactory, processManager, directoryFactory, manager)
	installationSteps := installationsteps.New()
	addonManager := addonmanager.New(installationSteps)
	mode := setupmatlab.New(osFacade, messageCatalog, loggerFactory, directoryFactory, watchdogWatchdog, globalMATLAB, addonManager)
	modeSelector := modeselector.New(factory, parserParser, telemetryFactory, watchdog3, orchestratorOrchestrator, osFacade, lifecycleSignaler, loggerFactory, mode)
	application := &Application{
		ModeSelector:              modeSelector,
		MessageCatalog:            messageCatalog,
		MATLABClientFactory:       matlabsessionclientFactory,
		HTTPClientFactory:         clientFactory,
		HTTPServerFactory:         serverFactory,
		LoggerFactory:             loggerFactory,
		LocalMATLABSessionStarter: starter,
	}
	return application
}

// wire.go:

type Application struct {
	ModeSelector        *modeselector.ModeSelector
	MessageCatalog      *messagecatalog.MessageCatalog
	MATLABClientFactory *matlabsessionclient.Factory
	HTTPClientFactory   *client.Factory
	HTTPServerFactory   *server.Factory
	LoggerFactory       *logger.Factory
	// Exposed for integration testing
	LocalMATLABSessionStarter *localmatlabsession.Starter
}

type ApplicationDefinition interface {
	Name() string
	Title() string
	Instructions() string
	Features() definition.Features
	Parameters() []entities.Parameter
	Dependencies(resources definition.DependenciesProviderResources) (any, error)
	Tools(resources definition.ToolsProviderResources) []tools.Tool
}
