// Copyright 2026 The MathWorks, Inc.

package telemetryendpoint

import (
	"bytes"
	"errors"
	"fmt"
	"net/url"
	"os"
	"strconv"
)

const generatedSource = `// Code generated by generate-telemetry-endpoint; DO NOT EDIT.

//go:build release

package defaultparameters

const defaultTelemetryCollectorEndpoint = %s
`

// Generate fails on an empty or malformed endpoint so a misconfigured release
// build never ships a binary that cannot reach the collector.
func Generate(outputPath, endpoint string) error {
	if err := validateEndpoint(endpoint); err != nil {
		return err
	}

	source := fmt.Sprintf(generatedSource, strconv.Quote(endpoint))
	if err := os.WriteFile(outputPath, []byte(source), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}

	return nil
}

// A missing build tag silently selects the empty default, which nothing else catches.
func Verify(binaryPath, endpoint string) error {
	if err := validateEndpoint(endpoint); err != nil {
		return err
	}

	binary, err := os.ReadFile(binaryPath) //nolint:gosec // caller is the build, which controls the path
	if err != nil {
		return fmt.Errorf("reading %s: %w", binaryPath, err)
	}

	if !bytes.Contains(binary, []byte(endpoint)) {
		return fmt.Errorf("%s was built without the telemetry collector endpoint", binaryPath)
	}

	return nil
}

func validateEndpoint(endpoint string) error {
	if endpoint == "" {
		return errors.New("telemetry collector endpoint is empty")
	}

	parsed, err := url.Parse(endpoint)
	if err != nil {
		return fmt.Errorf("telemetry collector endpoint %q is not a valid URL: %w", endpoint, err)
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return fmt.Errorf("telemetry collector endpoint %q must use http or https", endpoint)
	}
	if parsed.Host == "" {
		return fmt.Errorf("telemetry collector endpoint %q has no host", endpoint)
	}

	return nil
}
